### ISSUE TITLE
Add New Fields to Payment Sources

### ISSUE THREAD

**Issue by ahoshaiyan** [moyasar/moyasar-ios-sdk#29]
We need to add some new and old fields to our payment source classes.

## ApiCreditCardSource
- company: String?
- gateway_id: String?
- reference_number: String?
- response_code: String?
- authorization_code: String?

## ApiApplePaySource
- gateway_id: String?
- reference_number: String?
- response_code: String?
- authorization_code: String?

This should be a simple and straight forward change, once done we should release immediately

**Comment by AbdulazizAlrabiah** [comment]
PR: https://github.com/moyasar/moyasar-ios-sdk/pull/30
